repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        stages: [manual]
        args:
          - "--py37-plus"

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [manual]
        args:
          - --safe
          - --quiet
        files: ^((custom_components|script|tests)/.+)?[^/]+\.py$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        stages: [manual]
        args:
          - --quiet-level=2
          - --ignore-words-list=hass,ba,fo,mabe

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
        stages: [manual]
      - id: requirements-txt-fixer
        stages: [manual]
      - id: check-ast
        stages: [manual]
      - id: mixed-line-ending
        stages: [manual]
        args:
          - --fix=lf