name: sensor.wienerlinien
description: A platform which allows you to get information about next departure from spesified stop.
type: component
keywords:
  - sensor
  - wienerlinien
  - departure
author:
  name: ludeeus
  email: ludeeus@gmail.com
  homepage: https://ludeeus.github.io
license: MIT
files:
  - custom_components/wienerlinien/sensor.py
