default_config:
logger:
  default: error
  logs:
    custom_components.wienerlinien: debug



sensor:
  - platform: wienerlinien
    apikey: 2190400
    stops: '4429'
    firstnext: first
  - platform: wienerlinien
    apikey: 2190400
    stops: '4429'
    firstnext: next