name: Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  checks: write
  contents: write

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Run ${{ matrix.checks }}
    strategy:
      matrix:
        checks:
          - pyupgrade
          - black
          - codespell
          - check-json
          - requirements-txt-fixer
          - check-ast
          - mixed-line-ending
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        id: python
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: |
          python3 -m pip install pre-commit
          pre-commit install-hooks --config .pre-commit-config.yaml
      - name: Run the check (${{ matrix.checks }})
        run: pre-commit run --hook-stage manual ${{ matrix.checks }} --all-files --config .pre-commit-config.yaml 