name: Validate

on:
  pull_request:
  push:
  schedule:
    - cron:  '30 16 */3 * *'

jobs:
  validate-hassfest:
    runs-on: "ubuntu-latest"
    name: "With hassfest"
    steps:
    - name: "Check out repository"
      uses: "actions/checkout@v2"

    - name: "Hassfest validation"
      uses: "home-assistant/actions/hassfest@master"

  validate-hacs:
    runs-on: "ubuntu-latest"
    name: "With HACS"
    steps:
    - name: "Check out repository"
      uses: "actions/checkout@v3"

    - name: "HACS validation"
      uses: "hacs/action@main"
      with:
        category: "integration"